/// Flutter icons MoveIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoveIcons
///      fonts:
///       - asset: fonts/MoveIcons.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class MoveIcons {
  MoveIcons._();

  static const _kFontFam = 'MoveIcons';
  static const String? _kFontPkg = null;

  static const IconData steel = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData powpow3 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healing = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ethereal_outlined = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData physical = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ethereal = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData powpow2 = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fire = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healing_rounder = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healing_alt = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burning_eye = IconData(0xe950, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_adjust = IconData(0xf020, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flora = IconData(0xf06c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ice = IconData(0xf2dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData psychic = IconData(0xf3a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric = IconData(0xf3be, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
